/*
 * This code was generated by
 *  ___ ___   _   ___ _  _    _____ _   _    _  ___   ___      _   ___ ___      ___   _   ___     ___ ___ _  _ ___ ___    _ _____ ___  ___ 
 * | _ \ __| /_\ / __| || |__|_   _/_\ | |  | |/ | \ / / |    /_\ | _ ) __|___ / _ \ /_\ |_ _|__ / __| __| \| | __| _ \  /_\_   _/ _ \| _ \
 * |   / _| / _ \ (__| __ |___|| |/ _ \| |__| ' < \ V /| |__ / _ \| _ \__ \___| (_) / _ \ | |___| (_ | _|| .` | _||   / / _ \| || (_) |   /
 * |_|_\___/_/ \_\___|_||_|    |_/_/ \_\____|_|\_\ |_| |____/_/ \_\___/___/    \___/_/ \_\___|   \___|___|_|\_|___|_|_\/_/ \_\_| \___/|_|_\
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import Domain from "../base/Domain";
import Messaging from "./api/Messaging";
import Authentix from "./api/Authentix";

class ApiBase extends Domain {
  _messaging?: Messaging;
  _authentix?: Authentix;

  /**
   * Initialize api domain
   *
   * @param reach - The reach client
   */
  constructor(reach: any) {
    super(reach, "https://api.reach.talkylabs.com");
  }

  get messaging(): Messaging {
    this._messaging = this._messaging || new Messaging(this);
    return this._messaging;
  }
  
  get authentix(): Authentix {
    this._authentix = this._authentix || new Authentix(this);
    return this._authentix;
  }
}

export = ApiBase;
